const tiers = [
    { tier: 1, reward: "Perk", status: "locked"},
    { tier: 2, reward: "Perk", status: "locked"},
    { tier: 3, reward: "Perk", status: "locked"},
    { tier: 4, reward: "Perk", status: "locked"},
    { tier: 5, reward: "Perk", status: "locked"},
    { tier: 6, reward: "Perk", status: "locked"},
    { tier: 7, reward: "Perk", status: "locked"},
    { tier: 8, reward: "Perk", status: "locked"},
    { tier: 9, reward: "Perk", status: "locked"},
    { tier: 10, reward: "Perk", status: "locked"},
    { tier: 11, reward: "Perk", status: "locked"},
    { tier: 12, reward: "Perk", status: "locked"},
    { tier: 13, reward: "Perk", status: "locked"},
    { tier: 14, reward: "Perk", status: "locked"},
    { tier: 15, reward: "Perk", status: "locked"},
    { tier: 16, reward: "Perk", status: "locked"},
    { tier: 17, reward: "Perk", status: "locked"},
    { tier: 18, reward: "Perk", status: "locked"},
    { tier: 19, reward: "Perk", status: "locked"},
    { tier: 20, reward: "Perk", status: "locked"},
    { tier: 21, reward: "Perk", status: "locked"},
    { tier: 22, reward: "Perk", status: "locked"},
];

module.exports = tiers;